# Generated by Django 4.2.13 on 2024-05-26 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami '+9989999999' formatida kiritilishi kerak. 15 tagacha raqamga ruxsat beriladi.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon raqami'),
        ),
    ]
