# Generated by Django 4.2.13 on 2024-05-12 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
            },
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Nomi')),
                ('image', models.ImageField(blank=True, upload_to='Stuff/')),
                ('description', models.TextField(help_text='bu yerga mahsulotning harakteristikasini yozilishi kerak', verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Jihoz',
                'verbose_name_plural': 'Jihozlar',
            },
        ),
        migrations.CreateModel(
            name='RoomStuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(default=1, verbose_name='Miqdor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.room', verbose_name='Xona')),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.stuff', verbose_name='Jihoz')),
            ],
            options={
                'verbose_name': 'Xona jihozi',
                'verbose_name_plural': 'Xona jihozlari',
            },
        ),
        migrations.CreateModel(
            name='InvalidStuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(default=1, verbose_name='Miqdori')),
                ('description', models.TextField(help_text='Yaroqsizga chiqarish sababi', verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaroqsizga chiqarilgan vaqt')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.room', verbose_name='Xona')),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.stuff', verbose_name='Jihoz')),
            ],
            options={
                'verbose_name': 'Yaroqsiz Jihozlar',
            },
        ),
    ]
