# Generated by Django 4.2.13 on 2024-05-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nomi')),
                ('measure', models.CharField(choices=[('g', 'Gramm'), ('mg', 'Milligramm'), ('l', 'Liter'), ('ml', 'Milliliter')], default='g', max_length=3, verbose_name="O'lchov birligi")),
            ],
            options={
                'verbose_name': 'Dori vositasi',
                'verbose_name_plural': 'Dori vositalari',
            },
        ),
        migrations.AlterModelOptions(
            name='invalidstuff',
            options={'verbose_name': 'Yaroqsiz Jihoz', 'verbose_name_plural': 'Yaroqsiz Jihozlar'},
        ),
    ]
