# Generated by Django 4.2.13 on 2024-05-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_alter_medicine_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='aware_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=15, verbose_name='Ogohlantirish miqdori'),
        ),
    ]
