# Generated by Django 4.2.13 on 2024-05-22 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_medicine_aware_before_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='miqdor')),
                ('available_till', models.DateField(verbose_name='Yaroqlilik muddati')),
                ('status', models.IntegerField(choices=[(0, 'Yaroqlilik muddati tugagan'), (1, 'Active'), (2, 'Tugatilgan')], default=1, verbose_name='Xolati')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.medicine', verbose_name='Dori')),
            ],
            options={
                'verbose_name': 'Dori Partiyasi',
                'verbose_name_plural': 'Dorilar Partiyalari',
            },
        ),
    ]
