# Generated by Django 4.2.13 on 2024-05-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0007_batchmedicine_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchmedicine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Keltirilgan vaqt'),
        ),
    ]
