# Generated by Django 4.2.13 on 2024-05-22 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_attandace'),
        ('resource', '0008_batchmedicine_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='miqdor')),
                ('measure', models.CharField(choices=[('g', 'Gramm'), ('mg', 'MilliGramm'), ('l', 'Liter'), ('ml', 'MilliLiter'), ('unit', 'Dona')], default='g', max_length=5, verbose_name="O'lchov birligi")),
                ('description', models.TextField(verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Foydalanigan vaqti')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.medicine', verbose_name='Dori')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Foydalanilgan dori',
                'verbose_name_plural': 'Fodalanilgan dorilar',
            },
        ),
    ]
