# Generated by Django 4.2.13 on 2024-05-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0009_medicineusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchmedicine',
            name='available_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='mavjud miqdori'),
        ),
        migrations.AddField(
            model_name='batchmedicine',
            name='available_measure',
            field=models.CharField(choices=[('g', 'Gramm'), ('mg', 'MilliGramm'), ('l', 'Liter'), ('ml', 'MilliLiter'), ('unit', 'Dona')], default='g', max_length=5, verbose_name="Mavjud miqdor o'lchovi"),
        ),
        migrations.AlterField(
            model_name='batchmedicine',
            name='measure',
            field=models.CharField(choices=[('g', 'Gramm'), ('mg', 'MilliGramm'), ('l', 'Liter'), ('ml', 'MilliLiter'), ('unit', 'Dona')], default='g', max_length=5, verbose_name="Miqdor o'lchovi"),
        ),
    ]
