# Generated by Django 4.2.13 on 2024-05-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0011_medicine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='aware_before_days',
            field=models.PositiveBigIntegerField(default=3, help_text='Dorining yaroqlilik muddati tugashidan necha kun avval ogohlantirlishi kerakligini kiriting', verbose_name='Kun avval ogohlantir'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='image',
            field=models.ImageField(blank=True, upload_to='Stuff/', verbose_name='rasm'),
        ),
    ]
