# Generated by Django 4.2.13 on 2024-05-26 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0012_alter_medicine_aware_before_days_alter_stuff_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Sababi')),
                ('tracked_at', models.DateTimeField(auto_now_add=True, verbose_name='Qayd etilgan vaqt')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.batchmedicine', verbose_name='Partiya')),
            ],
            options={
                'verbose_name': 'Yaroqsiz dori',
                'verbose_name_plural': 'Yaroqsiz dorilar',
            },
        ),
    ]
