# Generated by Django 4.2.13 on 2024-05-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0013_invalidmedicine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicineusage',
            options={'verbose_name': 'Foydalanilgan dori', 'verbose_name_plural': 'Foydalanilgan dorilar'},
        ),
        migrations.AddField(
            model_name='invalidmedicine',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Miqdor'),
        ),
        migrations.AddField(
            model_name='invalidmedicine',
            name='measure',
            field=models.CharField(choices=[('g', 'Gramm'), ('mg', 'MilliGramm'), ('l', 'Liter'), ('ml', 'MilliLiter'), ('unit', 'Dona')], default='g', max_length=5, verbose_name="O'lchov birligi"),
        ),
    ]
