# Generated by Django 4.2.13 on 2024-05-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0014_alter_medicineusage_options_invalidmedicine_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidmedicine',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.medicine', verbose_name='Dori'),
        ),
    ]
