# Generated by Django 4.2.13 on 2024-05-27 05:39

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0015_invalidmedicine_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invalidstuff',
            name='stuff',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='room', chained_model_field='room', null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.stuff', verbose_name='Jihoz'),
        ),
    ]
