# Generated by Django 4.2.13 on 2024-05-27 08:23

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0017_alter_invalidstuff_stuff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invalidmedicine',
            name='batch',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='medicine', chained_model_field='medicine', null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.batchmedicine', verbose_name='Partiya'),
        ),
    ]
