# Generated by Django 4.2.13 on 2024-05-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0018_alter_invalidmedicine_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invalidmedicine',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.batchmedicine', verbose_name='Partiya'),
        ),
        migrations.AlterField(
            model_name='invalidstuff',
            name='stuff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.stuff', verbose_name='Jihoz'),
        ),
    ]
