# Generated by Django 4.2.13 on 2024-05-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_attandace'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='visible_password',
            field=models.CharField(max_length=150, null=True, verbose_name='Parol'),
        ),
    ]
