# Generated by Django 4.2.13 on 2024-05-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_visible_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='visible_password',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Parol'),
        ),
    ]
