"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

load_dotenv()
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", 'ZuFY8WQmPpHjZx3c6TnY7gMB-4zRfJdXK2LvA9oNSsVmYqOw5e')

DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'ckeditor',
    'ckeditor_uploader', 

    'account',
    'staff',
    'resource',
    'finance',
    'showcase_project',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': False,  
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ('uz', 'Uzbek'),
    ('ru', 'Russian'),
    ('en', 'Engish'),
]


LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]
EXCLUDE_PATHS = [
    'env',  # Exclude the 'env' directory
    'dist-info',  # Exclude directories ending with 'dist-info'
]

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',  # Optionally use a different skin
        'toolbar': 'Custom',  # Custom toolbar
        'height': 400,
        'width': '100%',
        'toolbar_Custom': [
            {'name': 'document', 'items': ['Source', '-', 'Preview', '-', 'Print', '-', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'basicstyles', 'items': ['Bold', 'Italic', 'Underline', '-', 'RemoveFormat']},
            {'name': 'paragraph', 'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert', 'items': ['Image', 'Table', 'HorizontalRule', 'SpecialChar']},
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
        ],
        'extraPlugins': ','.join([
            'uploadimage',  # Enable image uploads
            'autolink', 'autogrow', 'clipboard', 'dialog', 'dialogui', 'elementspath',
            'filetools', 'notification', 'notificationaggregator', 'filebrowser',
            'lineutils', 'link', 'widget'
        ]),
        'removeButtons': 'Subscript,Superscript',  # Optional: remove unused buttons
        'removePlugins': 'forms',  # Optional: remove unused plugins
        'allowedContent': True,  # Enable all content (disables ACF filtering)
        'autoGrow_minHeight': 400,  # Enable auto-grow feature
        'autoGrow_maxHeight': 800,
        'autoGrow_bottomSpace': 50,
        'filebrowserBrowseUrl': '/ckeditor/browse/',  # Optional: File browser URL
        'filebrowserUploadUrl': '/ckeditor/upload/',  # Optional: File upload URL
        'image_previewText': ' ',  # Preview text for uploaded images
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles', 'static')

MEDIA_URL = 'media/'
MEDIA_ROOT = 'media/'

# Define upload paths for images and files
CKEDITOR_UPLOAD_PATH = "uploads/"

# Optional: Restrict image and file sizes
CKEDITOR_IMAGE_BACKEND = "pillow"  # Choose between "pillow" or "image" for image processing
CKEDITOR_RESTRICT_BY_USER = True  # Restrict uploads to the authenticated user

# File browser settings (optional)
CKEDITOR_FILEBROWSER_URL = "/ckeditor/browse/"
CKEDITOR_FILEBROWSER_UPLOAD_URL = "/ckeditor/upload/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'account.CustomUser'


JAZZMIN_SETTINGS = {
    "site_title": "Dastyor Medical",
    "site_header": "Dastyor Medical",
    "site_brand": "Dastyor Medical",
    "welcome_sign": "Welcome to the Dastyor Medical",
    "topmenu_links": [
        {"model": "auth.User"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": False,
    "language_chooser": True
}
